title: HiveMQ MQTT Client
description: A fast, asynchronous, reactive mqtt client library
logo: assets/images/hivemq-mqtt-client-neg.svg
version: 1.1.3

remote_theme: SgtSilvio/just-the-docs@merged

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: false
  tokenizer_separator: /[\s\-/]+/
  button: true

color_scheme: dark

aux_links:
  "News":
    - "https://hivemq.github.io/hivemq-mqtt-client/news"
  "GitHub":
    - "https://github.com/hivemq/hivemq-mqtt-client"

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

github: [metadata]

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false