[versions]
awaitility = "4.3.0"
bouncycastle = "1.82"
dagger = "2.42"
equalsverifier = "4.2.2"
guava = "33.5.0-jre"
hivemq-extensionSdk = "4.7.2"
hivemq-testcontainer-junit5 = "2.0.0"
jctools = "2.1.2"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "6.0.1"
mockito = "5.20.0"
netty = "4.1.128.Final"
paho = "1.2.5"
pmd = "5.8.1"
reactiveStreams = "1.0.4"
reactor = "3.7.12"
reactor-adapter = "3.5.4"
rxjava = "2.2.21"
slf4j = "1.7.36"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsverifier" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hivemq-extensionSdk = { module = "com.hivemq:hivemq-extension-sdk", version.ref = "hivemq-extensionSdk" }
hivemq-testcontainer-junit5 = { module = "com.hivemq:hivemq-testcontainer-junit5", version.ref = "hivemq-testcontainer-junit5" }
jctools = { module = "org.jctools:jctools-core", version.ref = "jctools" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
netty-handler-proxy = { module = "io.netty:netty-handler-proxy", version.ref = "netty" }
netty-transport = { module = "io.netty:netty-transport", version.ref = "netty" }
netty-transport-native-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }
paho-client = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "paho" }
reactiveStreams = { module = "org.reactivestreams:reactive-streams", version.ref = "reactiveStreams" }
reactor = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
reactor-adapter = { module = "io.projectreactor.addons:reactor-adapter", version.ref = "reactor-adapter" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
bnd = { id = "biz.aQute.bnd.builder", version = "6.4.0" }
javadocLinks = { id = "io.github.sgtsilvio.gradle.javadoc-links", version = "0.8.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
mavenCentralPublishing = { id = "io.github.sgtsilvio.gradle.maven-central-publishing", version = "0.4.1" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
utf8 = { id = "com.github.sgtsilvio.gradle.utf8", version = "0.1.0" }
